### ISSUE TITLE
error adding an unhandled platform

### ISSUE THREAD

**Issue by RangerRick** [mhartington/cordova-config-utils#2]
If I tried to do `cordova platform add browser`, I get the following stack trace:

```
net.js:633
    throw new TypeError('invalid data');
          ^
TypeError: invalid data
    at Socket.write (net.js:633:11)
    at /Users/ranger/rcs/opennms-compass/hooks/after_prepare/011_update_config.js:300:24
    at arrayEach (/Users/ranger/rcs/opennms-compass/node_modules/lodash/index.js:1289:13)
    at Function.<anonymous> (/Users/ranger/rcs/opennms-compass/node_modules/lodash/index.js:3345:13)
    at /Users/ranger/rcs/opennms-compass/hooks/after_prepare/011_update_config.js:295:7
    at Object.<anonymous> (/Users/ranger/rcs/opennms-compass/hooks/after_prepare/011_update_config.js:304:3)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
Error: Hook failed with error code 1: /Users/ranger/git/opennms-compass/hooks/after_prepare/011_update_config.js
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:195:23
    at _rejected (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:797:24)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:823:30
    at Promise.when (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:1035:31)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:741:41)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:557:44
    at flush (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:355:11)
```

**Comment by surfjedi** [comment]
Still getting this issue?

net.js:617
throw new TypeError('invalid data');
^

TypeError: invalid data
at Socket.write (net.js:617:11)
at /Users/leeblazek/Sites/briebug/mvpclient/hooks/after_prepare/011_update_config.js:321:24
at Function.forEach (/Users/leeblazek/Sites/briebug/mvpclient/node_modules/lodash/dist/lodash.js:2331:13)
at /Users/leeblazek/Sites/briebug/mvpclient/hooks/after_prepare/011_update_config.js:316:7
at Object. (/Users/leeblazek/Sites/briebug/mvpclient/hooks/after_prepare/011_update_config.js:325:3)
at Module._compile (module.js:435:26)
at Object.Module._extensions..js (module.js:442:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:311:12)
at Function.Module.runMain (module.js:467:10)
Error: Hook failed with error code 1: /Users/leeblazek/Sites/briebug/mvpclient/hooks/after_prepare/011_update_config.js
at /Users/leeblazek/.nvm/versions/node/v4.2.0/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:195:23
at _rejected (/Users/leeblazek/.nvm/versions/node/v4.2.0/lib/node_modules/cordova/node_modules/q/q.js:797:24)
at /Users/leeblazek/.nvm/versions/node/v4.2.0/lib/node_modules/cordova/node_modules/q/q.js:823:30
at Promise.when (/Users/leeblazek/.nvm/versions/node/v4.2.0/lib/node_modules/cordova/node_modules/q/q.js:1035:31)
at Promise.promise.promiseDispatch (/Users/leeblazek/.nvm/versions/node/v4.2.0/lib/node_modules/cordova/node_modules/q/q.js:741:41)
at /Users/leeblazek/.nvm/versions/node/v4.2.0/lib/node_modules/cordova/node_modules/q/q.js:557:44
at flush (/Users/leeblazek/.nvm/versions/node/v4.2.0/lib/node_modules/cordova/node_modules/q/q.js:108:17)
at doNTCallback0 (node.js:417:9)
at process._tickCallback (node.js:346:13)

**Comment by surfjedi** [comment]
Has this been tested on the new xcode 7.1?

**Comment by surfjedi** [comment]
and node 4.2.1?

**Comment by mhartington** [comment]
Yeah it works with node 4x and xcode 7. What version of the plugin do you have?

**Comment by surfjedi** [comment]
looks like 2.1

  "_args": [
    [
      "cordova-config-utils@^2.1.0",
      "/Users/leeblazek/Sites/briebug/mvpclient"
    ]
  ],
  "_from": "cordova-config-utils@>=2.1.0 <3.0.0",
  "_id": "cordova-config-utils@2.1.0",
  "_inCache": true,
  "_location": "/cordova-config-utils",
  "_nodeVersion": "4.2.1",
  "_npmUser": {
    "email": "mikehartington@gmail.com",
    "name": "mhartington"
  },
  "_npmVersion": "2.14.7",
  "_phantomChildren": {},
  "_requested": {
    "name": "cordova-config-utils",
    "raw": "cordova-config-utils@^2.1.0",
    "rawSpec": "^2.1.0",
    "scope": null,
    "spec": ">=2.1.0 <3.0.0",
    "type": "range"
  },
  "_requiredBy": [
    "#DEV:/"

**Comment by surfjedi** [comment]
Ahh it appears I had an older lodasah version 1.0.1,  after updating that to the lastest it appears working

**Comment by adeelhussain** [comment]
@surfjedi can you please list here your cordova, npm and lodash versions, i am also facing the same issue

**Comment by RangerRick** [comment]
Yeah, it turns out the problem also occurs if for other reasons you have lodash 4 installed, because _.indexBy has been replaced by _.keyBy in the newer lodash.

I've updated my fork of this project to just use the latest lodash, and change .indexBy to .keyBy, but I don't know if it's the best thing to do that, really.  :/

**Comment by mhartington** [comment]
@RangerRick you do have commit access to this repo, so feel free to push any changes upstream :+1:

**Comment by RangerRick** [comment]
Yeah, I know, just wasn't sure if it would mess with anything.  :)  I'll go ahead and push my update then.

**Comment by RangerRick** [comment]
OK, that's my bump.  Everything seems to be working nicely with that.  @mhartington should I bump the version to 2.2.0 and tag?

**Comment by mhartington** [comment]
I can push a new release in a bit

**Comment by AliakseiT** [comment]
New release with this fix would be appreciated.

**Comment by zwacky** [comment]
here too, keep failing due to lodash dep. +1 for upstream release 💕

**Comment by mhartington** [comment]
Sorry for the delay.
https://www.npmjs.com/package/cordova-config-utils

2.2.1 is up
